// Generated by Tobia APK Factory

package com.tobia.factory_test

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.math.roundToInt

// Dark Theme Color Scheme
private val DarkColorScheme = darkColorScheme(
    primary = Color(0xFF00FF88),
    secondary = Color(0xFF00CCFF),
    tertiary = Color(0xFF00CCFF),
    onPrimary = Color.Black,
    onBackground = Color.White,
    onSurface = Color.White,
    onSecondary = Color.Black,
    background = Color(0xFF000000),
    surface = Color(0xFF1A1A2E),
    error = Color(0xFFFF4444),
)

@Composable
fun TobiaDarkApp(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = DarkColorScheme,
        content = content
    )
}



class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            TobiaDarkApp {
                CalculatorScreen()
            }
        }
    }
}


// ── Safe Expression Evaluator ─────────────────────────────────

object ExprParser {
    private var pos = 0
    private var input = ""

    fun evaluate(expr: String): Double {
        input = expr.replace(" ", "")
        if (input.isEmpty()) return 0.0
        pos = 0
        val result = parseExpression()
        if (pos != input.length) return Double.NaN
        return result
    }

    private fun parseExpression(): Double {
        var left = parseTerm()
        while (pos < input.length) {
            val op = input[pos]
            if (op != '+' && op != '-') break
            pos++
            val right = parseTerm()
            left = if (op == '+') left + right else left - right
        }
        return left
    }

    private fun parseTerm(): Double {
        var left = parseFactor()
        while (pos < input.length) {
            val op = input[pos]
            if (op != '*' && op != '/') break
            pos++
            val right = parseFactor()
            if (right == 0.0 && op == '/') return Double.NaN
            left = if (op == '*') left * right else left / right
        }
        return left
    }

    private fun parseFactor(): Double {
        if (pos >= input.length) return 0.0
        if (input[pos] == '(') {
            pos++
            val result = parseExpression()
            if (pos < input.length && input[pos] == ')') pos++
            return result
        }
        if (input[pos] == '-') {
            pos++
            return -parseFactor()
        }
        val start = pos
        while (pos < input.length && (input[pos].isDigit() || input[pos] == '.')) pos++
        if (start == pos) return 0.0
        return input.substring(start, pos).toDoubleOrNull() ?: 0.0
    }
}

data class HistoryEntry(
    val expression: String, val result: String, val timestamp: Long
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CalculatorScreen() {
    var display by remember { mutableStateOf("0") }
    var expression by remember { mutableStateOf("") }
    var isTipMode by remember { mutableStateOf(false) }
    var tipAmount by remember { mutableStateOf("") }
    var tipPercent by remember { mutableStateOf(15f) }
    var splitCount by remember { mutableStateOf(1) }
    var showClearConfirm by remember { mutableStateOf(false) }
    var historyList by remember { mutableStateOf(mutableListOf<HistoryEntry>()) }
    val primary = Color(0xFF00FF88)

    Column(
        modifier = Modifier.fillMaxSize()
            .background(MaterialTheme.colorScheme.background)
    ) {
        // Display area
        Surface(
            modifier = Modifier.fillMaxWidth().weight(0.3f),
            color = MaterialTheme.colorScheme.surface,
            shape = RoundedCornerShape(bottomStart = 24.dp, bottomEnd = 24.dp)
        ) {
            Column(
                modifier = Modifier.fillMaxSize().padding(16.dp),
                verticalArrangement = Arrangement.Bottom,
                horizontalAlignment = Alignment.End
            ) {
                if (isTipMode) {
                    Text("Amount", style = MaterialTheme.typography.labelMedium,
                        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f))
                    Spacer(modifier = Modifier.height(4.dp))
                    OutlinedTextField(
                        value = tipAmount, onValueChange = { tipAmount = it },
                        modifier = Modifier.fillMaxWidth(), singleLine = true,
                        colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = primary, cursorColor = primary),
                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal)
                    )
                    Spacer(modifier = Modifier.height(16.dp))
                    Row(modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("Tip %", color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f))
                        Text("${tipPercent.roundToInt()}%", color = primary, fontWeight = FontWeight.Bold)
                    }
                    Slider(value = tipPercent, onValueChange = { tipPercent = it },
                        valueRange = 0f..50f, steps = 49,
                        colors = SliderDefaults.colors(thumbColor = primary, activeTrackColor = primary))
                    
                    val amountVal = tipAmount.toDoubleOrNull() ?: 0.0
                    val tipVal = amountVal * (tipPercent / 100.0)
                    val totalVal = amountVal + tipVal
                    val perPerson = totalVal / splitCount
                    Spacer(modifier = Modifier.height(12.dp))
                    Text("Total" + ": " + formatMoney(totalVal),
                        style = MaterialTheme.typography.headlineSmall,
                        color = primary, fontWeight = FontWeight.Bold)
                    
                } else {
                    Text(expression, style = MaterialTheme.typography.bodyLarge,
                        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f),
                        maxLines = 2, overflow = TextOverflow.Ellipsis)
                    Spacer(modifier = Modifier.height(8.dp))
                    Text(display, style = MaterialTheme.typography.displayMedium,
                        color = MaterialTheme.colorScheme.onSurface,
                        fontWeight = FontWeight.Bold, fontFamily = FontFamily.Monospace)
                }
            }
        }

        // Mode toggle
        Row(modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically) {
            TextButton(onClick = { isTipMode = !isTipMode }) {
                Text(if (isTipMode) "Std" else "Tip Calc", color = primary)
            }
            if (isTipMode) {
                TextButton(onClick = { tipAmount = ""; tipPercent = 15f; splitCount = 1 }) {
                    Text("C", color = Color(0xFFFF4444))
                }
            }
        }

        // Keypad
        if (isTipMode) {
            CalculatorKeypad(
                onNumber = { digit -> tipAmount = if (tipAmount == "0") digit.toString() else tipAmount + digit },
                onOperator = { }, onClear = { tipAmount = "" }, onEquals = { },
                onDecimal = { if (!tipAmount.contains(".")) tipAmount += "." },
                onDelete = { if (tipAmount.isNotEmpty()) tipAmount = tipAmount.dropLast(1) },
                primary = primary
            )
        } else {
            CalculatorKeypad(
                onNumber = { digit -> expression += digit; display = expression },
                onOperator = { op -> expression += op; display = expression },
                onClear = { expression = ""; display = "0" },
                onEquals = {
                    if (expression.isNotEmpty()) {
                        val result = ExprParser.evaluate(expression)
                        if (result.isNaN()) display = "Error"
                        else {
                            val formatted = formatResult(result); display = formatted
                            if (false) {
                                historyList.add(HistoryEntry(expression = expression,
                                    result = formatted, timestamp = System.currentTimeMillis()))
                            }
                        }
                        expression = ""
                    }
                },
                onDecimal = { if (!expression.endsWith(".")) { expression += "."; display = expression } },
                onDelete = {
                    if (expression.isNotEmpty()) {
                        expression = expression.dropLast(1)
                        display = if (expression.isEmpty()) "0" else expression
                    }
                },
                primary = primary
            )
        }

        
    }

    // Clear confirm dialog
    if (showClearConfirm) {
        AlertDialog(
            onDismissRequest = { showClearConfirm = false },
            title = { Text("C") },
            text = { Text("No history yet") },
            confirmButton = { TextButton(onClick = { historyList.clear(); showClearConfirm = false })
                { Text("Yes") } },
            dismissButton = { TextButton(onClick = { showClearConfirm = false })
                { Text("No") } }
        )
    }
}

@Composable
fun CalculatorKeypad(
    onNumber: (Int) -> Unit, onOperator: (String) -> Unit,
    onClear: () -> Unit, onEquals: () -> Unit,
    onDecimal: () -> Unit, onDelete: () -> Unit,
    primary: Color
) {
    Column(modifier = Modifier.fillMaxWidth().padding(8.dp),
        verticalArrangement = Arrangement.spacedBy(4.dp)) {
        val buttons = listOf(
            listOf("7" to "N", "8" to "N", "9" to "N", "/" to "O"),
            listOf("4" to "N", "5" to "N", "6" to "N", "*" to "O"),
            listOf("1" to "N", "2" to "N", "3" to "N", "-" to "O"),
            listOf("0" to "N", "." to "D", "=" to "E", "+" to "O")
        )
        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(4.dp)) {
            CalcButton(text = "CE", modifier = Modifier.weight(1f),
                color = Color(0xFFFF4444).copy(alpha = 0.8f), onClick = onClear)
            CalcButton(text = "DEL", modifier = Modifier.weight(1f),
                color = Color(0xFFFF4444).copy(alpha = 0.5f), onClick = onDelete)
            CalcButton(text = "(", modifier = Modifier.weight(1f),
                color = primary.copy(alpha = 0.3f), onClick = { onOperator("(") })
            CalcButton(text = ")", modifier = Modifier.weight(1f),
                color = primary.copy(alpha = 0.3f), onClick = { onOperator(")") })
        }
        for (row in buttons) {
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                for ((label, btnType) in row) {
                    val buttonColor = when (btnType) {
                        "N" -> MaterialTheme.colorScheme.surface
                        "O" -> primary.copy(alpha = 0.2f)
                        "E" -> primary
                        "D" -> primary.copy(alpha = 0.3f)
                        else -> MaterialTheme.colorScheme.surface
                    }
                    val textColor = when (btnType) {
                        "O" -> primary
                        "E" -> Color.Black
                        else -> MaterialTheme.colorScheme.onSurface
                    }
                    CalcButton(text = label, modifier = Modifier.weight(1f),
                        color = buttonColor, contentColor = textColor,
                        onClick = { when (btnType) {
                            "N" -> onNumber(label.toInt())
                            "O" -> onOperator(label)
                            "E" -> onEquals()
                            "D" -> onDecimal()
                        } })
                }
            }
        }
    }
}

@Composable
fun CalcButton(text: String, modifier: Modifier = Modifier,
    color: Color = MaterialTheme.colorScheme.surface,
    contentColor: Color = MaterialTheme.colorScheme.onSurface,
    onClick: () -> Unit) {
    Surface(modifier = modifier.height(56.dp).clip(RoundedCornerShape(12.dp)),
        color = color, shape = RoundedCornerShape(12.dp), onClick = onClick) {
        Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
            Text(text, style = MaterialTheme.typography.titleMedium,
                color = contentColor, fontWeight = FontWeight.SemiBold)
        }
    }
}

fun formatResult(value: Double): String {
    return if (value == value.toLong().toDouble()) value.toLong().toString()
    else "%.6f".format(value).trimEnd('0').trimEnd('.')
}

fun formatMoney(value: Double): String {
    val whole = value.toLong()
    val frac = ((value - whole) * 100).roundToInt()
    return "$whole.${frac.toString().padStart(2, '0')}"
}
